### PR TITLE
Fix protected fields

### LINKED ISSUE #82: Protect elements of form that contain important data (accountID?)
When a new account is created, the specified account ID in the form should have to match the accountID sent in the query string

### PR DESCRIPTION
**Pull request by cadecrandall**
### Description
The form now prevents the user from editing protected fields and does not send changes to protected fields in the request. 

### Issues resolved
- Closes #82

### CODE REVIEW

File: src/main/java/data/Account.java [hunk 1]
```diff
@@ -198,13 +198,13 @@ public String buildJsonConfig() {
...
   /**
-   * Update existing account information, preventing changes to legacyAccountId
-   * and nextGenAccountId
+   * Update existing account information.
+   * Changes to legacyCustomerId, nextGenCustomerId, vendorId, and accountId
+   *      are disabled in the UI and not propagated to the backend.
+   *
    * @param request contains form data to edit existing account
    */
   public void updateExistingAccount(HttpServletRequest request) {
```
Comment (ianjjohnson) [inline src/main/java/data/Account.java:207]: please add a TODO here to prevent changes in the backend as well (even though we're not going to get to it, I think it's important to clarify it as a next step)
